// Create Employee
POST http://localhost:8080/api/employees/create
Content-Type: application/json


{
    "firstName": "Jack",
    "lastName": "Hammer",
    "email": "jack.hammer@example.com",
    "positionId": "NqsBAoSkYBnvkaxlqbWP",
    "departmentId": "36eL32Ass8WtbPJrxBt9"
}